#! /bin/bash

# Change directories to the root of the project
SRC=$(dirname $0)
cd $SRC/..

# Fetch the current version for which docs are being generated
version=$(grep -o -E '[0-9]+\.[0-9]+\.[0-9]+[a-zA-Z_-]*' chula/__init__.py)

# Specify the output location (this will include a version number)
dest=/tmp/chula-docs-build/$version
mkdir -p $dest

# Generate documentation
sphinx-build -E -b html docs $dest

# Print browsable path
echo
echo "file://$dest/index.html"

