#!/usr/bin/env python
#
# Run all Chula unit tests (including doctests)

import os
import sys

from chula import testutils

if __name__ == "__main__":
    # Search the passed paths, or the current working directory
    path = sys.argv[1:]
    if len(path) == 0:
        path = os.getcwd()

    tests = testutils.TestFinder(path)
    tests.run()
